---
driver:
  name: vagrant
#  network:
#  - ["forwarded_port", {guest: 80, host: 8080}]
#  - ["forwarded_port", {guest: 27017, host: 27018}]
#  - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: chef/centos-6.5
  run_list:
- name: centos-6.6
  run_list:
- name: centos-7.1
  run_list:
- name: ubuntu-14.04
  run_list:

suites:
- name: php
  data_bags_path: "test/integration/default/data_bags"
  roles_path: "test/integration/default/roles"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
  run_list:
    - recipe[minitest-handler]
    - role[kitchen]
    - role[main_server]
    - recipe[rails::vagrant]
  attributes:
    tags:
      - php
      - mysql
      - vagrant

- name: ror
  data_bags_path: "test/integration/default/data_bags"
  roles_path: "test/integration/default/roles"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
  run_list:
    - recipe[minitest-handler]
    - role[kitchen]
    - role[app1_node]
    - recipe[rails::vagrant]
  attributes:
    tags:
      - ror
      - postgresql
      - vagrant
