LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

SingleSpaceBeforeFirstArg:
  Enabled: false

TrailingComma:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/LeadingCommentSpace:
  Exclude:
    - 'Berksfile'

AllCops:
  Exclude:
    - 'Berksfile'
    - 'Vagrantfile'
    - '.kitchen/**/*'
    - 'lib/**/*'


